<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		// $this->call('UserTableSeeder');
		$this->call('MenusTableSeeder');
		$this->call('TweetsTableSeeder');
		$this->call('Gd_productosTableSeeder');
		$this->call('EntidadesTableSeeder');
		$this->call('Users_entidadesTableSeeder');
		$this->call('BndsTableSeeder');
		$this->call('Emision_efectosTableSeeder');
		$this->call('Duracion_accionsTableSeeder');
		$this->call('Continuidad_efectosTableSeeder');
		$this->call('ReversibilidadsTableSeeder');
		$this->call('ProbabilidadsTableSeeder');
		$this->call('Intensidad_impactosTableSeeder');
		$this->call('FactorsTableSeeder');
		$this->call('RubrosTableSeeder');
		$this->call('EspecificosTableSeeder');
		$this->call('CaracteristicasTableSeeder');
		$this->call('EfectosTableSeeder');
		$this->call('MatrizsTableSeeder');
		$this->call('MitigacionsTableSeeder');
		$this->call('ClientesTableSeeder');
		$this->call('Reg_impactosTableSeeder');
		$this->call('Tipo_impactosTableSeeder');
		$this->call('Enc_impactosTableSeeder');
		$this->call('Ln_caracteristicasTableSeeder');
		$this->call('St_reg_impactosTableSeeder');
		$this->call('Doc_proyectosTableSeeder');
		$this->call('DocumentosTableSeeder');
		$this->call('Ln_dossiersTableSeeder');
		$this->call('SmsTableSeeder');
		$this->call('AchecksTableSeeder');
		$this->call('CumplimientosTableSeeder');
		$this->call('MchecksTableSeeder');
		$this->call('ChecksTableSeeder');
		$this->call('ChecklsTableSeeder');
		$this->call('NormasTableSeeder');
		$this->call('AreasTableSeeder');
		$this->call('Ca_ca_docsTableSeeder');
		$this->call('Ca_procedimientosTableSeeder');
		$this->call('Ca_materialesTableSeeder');
		$this->call('Ca_categoriaTableSeeder');
		$this->call('Ca_aa_docsTableSeeder');
		$this->call('Ca_plantasTableSeeder');
		$this->call('Ca_fuentes_fijasTableSeeder');
		$this->call('Ca_residuosTableSeeder');
		$this->call('Ca_consumiblesTableSeeder');
		$this->call('Ca_tpo_inconformidadesTableSeeder');
		$this->call('Cs_tpo_procedimientosTableSeeder');
		$this->call('Cs_tpo_docsTableSeeder');
		$this->call('Cs_grupo_normasTableSeeder');
		$this->call('Cs_normasTableSeeder');
		$this->call('Cs_elementos_inspeccionsTableSeeder');
		$this->call('Cs_cat_docsTableSeeder');
		$this->call('Cs_accidentesTableSeeder');
		$this->call('Cs_accionesTableSeeder');
		$this->call('Cs_enfermedadesTableSeeder');
		$this->call('Cs_tpo_bitacorasTableSeeder');
		$this->call('Cs_tpo_inconformidadesTableSeeder');
		$this->call('EmpleadosTableSeeder');
		$this->call('PuestosTableSeeder');
		$this->call('A_archivosTableSeeder');
		$this->call('A_estatus_docsTableSeeder');
		$this->call('A_st_archivosTableSeeder');
		$this->call('A_comentarios_archivosTableSeeder');
		$this->call('A_procedimientosTableSeeder');
		$this->call('A_comentarios_procedimientosTableSeeder');
		$this->call('A_rr_ambientalesTableSeeder');
		$this->call('A_comentarios_rrsTableSeeder');
		$this->call('Bitacora_ffsTableSeeder');
		$this->call('TurnosTableSeeder');
		$this->call('Bitacora_plantasTableSeeder');
		$this->call('Bitacora_residuosTableSeeder');
		$this->call('Bitacora_consumiblesTableSeeder');
		$this->call('Bitacora_pendientesTableSeeder');
		$this->call('Bit_stsTableSeeder');
		$this->call('Mapeo_historicosTableSeeder');
		$this->call('Bitacora_pendientes_hsTableSeeder');
		$this->call('A_no_conformidadesTableSeeder');
		$this->call('A_st_ncsTableSeeder');
		$this->call('Cs_tpo_deteccionsTableSeeder');
		$this->call('A_comentarios_ncsTableSeeder');
		$this->call('A_comentarios_pendientesTableSeeder');
		$this->call('S_procedimientosTableSeeder');
		$this->call('S_estatus_procedimientosTableSeeder');
		$this->call('S_comentarios_procedimientosTableSeeder');
		$this->call('S_registrosTableSeeder');
		$this->call('S_comentarios_registrosTableSeeder');
		$this->call('Bitacora_seguridadsTableSeeder');
		$this->call('Comentarios_bsTableSeeder');
		$this->call('S_st_bsTableSeeder');
		$this->call('S_documentosTableSeeder');
		$this->call('S_comentarios_documentosTableSeeder');
		$this->call('Bitacora_accidentesTableSeeder');
		$this->call('Bitacora_enfermedadesTableSeeder');
		$this->call('P_ambiental_correosTableSeeder');
		$this->call('P_correo_bitacorasTableSeeder');
		$this->call('BitacorasTableSeeder');
		$this->call('Ca_tpo_bitacorasTableSeeder');
		$this->call('Ca_tpo_noconformidadesTableSeeder');
		$this->call('Efecto_spsTableSeeder');
		$this->call('Imp_realsTableSeeder');
		$this->call('Imp_potencialsTableSeeder');
		$this->call('M_imp_potencialsTableSeeder');
		$this->call('M_imp_realsTableSeeder');
		$this->call('ProcesosTableSeeder');
		$this->call('Aa_procesosTableSeeder');
		$this->call('Aa_aspectosTableSeeder');
		$this->call('Aspectos_ambientalesTableSeeder');
		$this->call('Aa_emesTableSeeder');
		$this->call('Aa_condicionesTableSeeder');
		$this->call('Aa_impactosTableSeeder');
		$this->call('MesesTableSeeder');
		$this->call('Estatus_condicionesTableSeeder');
		$this->call('ImportanciaTableSeeder');
		$this->call('Rev_requisitosTableSeeder');
		$this->call('Rev_requisitos_lnsTableSeeder');
		$this->call('Estatus_requisitosTableSeeder');
		$this->call('Tpo_docsTableSeeder');
		$this->call('Rev_documentalsTableSeeder');
		$this->call('Rev_documentoal_lnsTableSeeder');
		$this->call('CondicionesTableSeeder');
		$this->call('R_documentosTableSeeder');
		$this->call('M_clase_mantosTableSeeder');
		$this->call('M_tpo_mantosTableSeeder');
		$this->call('M_estatusesTableSeeder');
		$this->call('M_mantenimientosTableSeeder');
		$this->call('M_objetivosTableSeeder');
		$this->call('SubequiposTableSeeder');
		$this->call('M_tpo_riesgosTableSeeder');
		$this->call('Manto_docsTableSeeder');
		$this->call('Bit_doc_accidentesTableSeeder');
		$this->call('A_rr_amb_docsTableSeeder');
		$this->call('A_archi_docsTableSeeder');
	}

}
